### ISSUE TITLE
Github markdown issues

### ISSUE THREAD

**Issue by syabro** [fulstech/markin#1]
1. Code doesn't highlited
2. Todo lists doesn't work
3. Emojis don't work

![](http://s.syabro.com/dd8jd.png)

![](http://s.syabro.com/i50z1.png)

**Comment by syabro** [comment]
Also help links leads to https://fulstech.wordpress.com/2016/02/25/markin-markdown-gherkin-hybrid-editor-for-jira but wordpress shows 404 because it asks a slash in the end

**Comment by fulstech** [comment]
Thank you a lot for the suggestions! We have fixed the link, and will add syntax highlighting for source code in next version - this is a very cool idea.

**Comment by fulstech** [comment]
syabro,

We are happy to inform you that the new version (1.1.1) has support syntax highlighting, checkbox, and emoji. We really appreciate your suggestions and we are looking forward to future ideas from you. Thank you.
