### ISSUE TITLE
Integrated MathJax.js library over CDN to slow

### ISSUE THREAD

**Issue by MarcelSchmaeing** [fulstech/markin#11]
Hi,

nearly every second request we have the problem that the CDN of the MathJax.js is to slow or doesn't even respond. 
In this time the whole detail page of a ticket is not displayed properly.

Maybe you can integrate this library into the plugin?

Greetings,

Marcel

**Comment by fulstech** [comment]
Thank you for your feedback. MathJax has been packaged inside as of Markin 3.0.0 to reduce the loading time. You can get the latest version at https://marketplace.atlassian.com/plugins/com.fulstech.jira-gherkin-custom-field/server/overview.

Please feel free to get back if you have any request. We always appreciate your suggestion.
