### ISSUE TITLE
JIRA- or GitHub-style at-mentions?

### ISSUE THREAD

**Issue by cfm** [fulstech/markin#15]
Neither JIRA-style `[~UserName]` nor GitHub-style `~user` at-mentions appear to work in a Markin-rendered field.  Is either syntax possible with Markin?

**Comment by yegeniy** [comment]
I can't get it to work with @fulstech either

**Comment by fulstech** [comment]
Thank you all for your feedback. This feature will be available in the next version, which we planned to publish in two weeks. We are sorry for the inconvenience and will work hard to make it come out as soon as possible.

If you have any other feature requests, do not hesitate to let us know, we will be very happy to support.

**Comment by kiler129** [comment]
Any ETA on this?

**Comment by corywright** [comment]
I would really like to see this as well.

**Comment by fulstech** [comment]
Hi everyone,

Thank you all for your interest. Please check out the latest version of Markin. You can mention a user using JIRA-style syntax [~username], or just simply type @ to trigger the autocomplete list of users.

**Comment by cfm** [comment]
Works beautifully.  Thank you!
