### ISSUE TITLE
New line not working properly

### ISSUE THREAD

**Issue by tfmf** [fulstech/markin#16]
Cannot add a simple new line, see bellow:

![markdown](https://cloud.githubusercontent.com/assets/7047895/20708065/1f2e4cd8-b626-11e6-82ff-b008bb77c7ff.gif)

**Comment by cfm** [comment]
I believe this is in fact [consistent with other Markdown implementations][dingus] and their inheritance of an [HTML-like attitude to whitespace][html-whitespace].

[dingus]: http://spec.commonmark.org/dingus/?text=**TEST1**%0A**TEST2**%0A**TEST3**
[html-whitespace]: https://www.w3.org/TR/CSS2/text.html#white-space-model

**Comment by fulstech** [comment]
Hi @tfmf,

To keep lines in separate paragraphs, please add an empty line between them.
