### ISSUE TITLE
blockquotes do not render

### ISSUE THREAD

**Issue by cfm** [fulstech/markin#17]
Compare (1) this Markdown—

    This looks like Red Hat bug no. 879633:

    > When sudo is used with sssd and a local user runs sudo, an e-mail is
    > sent to administrator, because sssd does not support sudo rules for
    > local users. It is not an error, only noise.

—and (2) this output here on GitHub—

This looks like Red Hat bug no. 879633:

> When sudo is used with sssd and a local user runs sudo, an e-mail is
> sent to administrator, because sssd does not support sudo rules for
> local users. It is not an error, only noise.

—to (3) this output with Markin:

![markin-no-blockquote](https://cloud.githubusercontent.com/assets/357435/20764261/7273fdd6-b6fb-11e6-9347-fbafd1eb4ba5.png)

(Ignore the hyperlink visible in [3] that I've omitted from [1] and [2].)

**Comment by fulstech** [comment]
Hi @cfm,

Thank you for your interest. Please check out the latest version to see if the issue is still present. If it is, could you please share with us the entire Markdown content?

**Comment by cfm** [comment]
I can no longer reproduce this bug as of Markin 6.0.0.  Thank you for following up.
