### ISSUE TITLE
Special characters are rendered as HTML entities

### ISSUE THREAD

**Issue by kiler129** [fulstech/markin#18]
Trying to use `"` results in `&quot;foo&quot;` in the output.

![2](https://cloud.githubusercontent.com/assets/1227834/20900249/2caac6bc-baf3-11e6-8983-bf76f6298332.png)
![1](https://cloud.githubusercontent.com/assets/1227834/20900250/2cab2e4a-baf3-11e6-8337-e52bed143d87.png)

This also applies to e.g. `<`, so issue makes code snippets unusable.

**Comment by fulstech** [comment]
Hi @kiler129,

Thank you for your interest. This issue has been fixed in the latest version.
