### ISSUE TITLE
Inline & block code style needs new defaults

### ISSUE THREAD

**Issue by kdubb** [fulstech/markin#19]
The current defaults leave **most** code blocks almost imperceptibly different than normal text.  Almost all all services change both the background and text colors to differentiate the text. As examples:

Style | Bitbucket (Server) | Github | Slack
------|-------------------|--------|------|
Inline Code | Grey background, _larger_ black text | Grey background, black text (e.g. `like this`) | Grey background, red text |
Block Code (No Language) | Grey background, _smaller_ black text | Grey, background, black text | Grey background, dark grey text |
Block Code (Language Selected) | Grey background, _smaller_ colored text | Grey background, colored text | Grey background, colored text |

No Markdown implementor leaves it the same colors as the original text.  I would suggest copying the `Bitbucket Server` style since your plugin is currently for `JIRA Server`.

These defaults, and the exceeding hard method required to change them without leaking changes into JIRA, is the reason we aren't using this plugin.

**Comment by kdubb** [comment]
Here is an example from Bitbucket Server:
<img width="298" alt="screen shot 2016-12-30 at 12 13 29 pm" src="https://cloud.githubusercontent.com/assets/787655/21571143/798581f8-ce89-11e6-9c24-20f1463bf52d.png">

**Comment by fulstech** [comment]
@kdubb,

We highly appreciate your suggestions. In the latest version (7.0.1), the style has been updated accordingly.

![demo-2 task2 - your company jira](https://cloud.githubusercontent.com/assets/17452401/21590135/782c0f08-d12b-11e6-8a97-24359342b964.jpg)
