### ISSUE TITLE
Converting from atlassian renderer conventions to markdown 

### ISSUE THREAD

**Issue by hooke** [fulstech/markin#2]
Hello,

Is it possible to convert old desriptions/comments written using atlassian wiki style renderer conventions into yours? For example, to convert atlassian style links `[text|URL]` into Markdown style `[text](URL)`?

Also, is it possible to insert picture into text, like wiki style renderer does: `!screenshot1.png|thumbnail!`?

Otherwise, it is painful to read old comments after changing renderer to Markin editor :disappointed:

**Comment by fulstech** [comment]
Thank you for making these suggestions - we appreciate it! All are feasible and we are working hard to make sure they will be available in the upcoming release.

**Comment by fulstech** [comment]
I'm happy to inform that the following Atlassian Wiki's syntax has been supported out of the box:

- Link `[text|URL]`
- Attachment thumbnail `!screenshot1.png|thumbnail!`
- Table `||header1||header2||`

We will continue working on Atlassian Wiki's syntax to make migration seamlessly as much as possible. If you have any request, don't hesitate to post it here - we will add it to future versions.
