### ISSUE TITLE
Enlarge size of default textarea for description fields

### ISSUE THREAD

**Issue by kdubb** [fulstech/markin#20]
The JIRA standard default size for the description field is 12 "rows" in the create dialog. Markin appears to be at 1em.

The larger description field is actually very handy for visually locating the field in the dialog.

**Comment by kdubb** [comment]
This issue is also seen in comment fields on the issue details page:

## Markin:
<img width="334" alt="screen shot 2017-01-01 at 1 59 25 pm" src="https://cloud.githubusercontent.com/assets/787655/21583013/992e2a08-d02a-11e6-918e-aa2ec214015b.png">

## JIRA Default:
<img width="590" alt="screen shot 2017-01-01 at 2 02 32 pm" src="https://cloud.githubusercontent.com/assets/787655/21583036/04dd8906-d02b-11e6-89e8-5bac05421942.png">

**Comment by kdubb** [comment]
Here are screenshots of the `description` field in the `Create -> Issue` dialog

## Markin:
<img width="447" alt="screen shot 2017-01-01 at 2 04 09 pm" src="https://cloud.githubusercontent.com/assets/787655/21583041/4f91890c-d02b-11e6-8842-de8a5a052ce8.png">

## JIRA Default:
<img width="657" alt="screen shot 2017-01-01 at 2 03 49 pm" src="https://cloud.githubusercontent.com/assets/787655/21583042/56512284-d02b-11e6-967d-928946fde02e.png">

**Comment by fulstech** [comment]
@kdubb,

Thank you for your feedback. Please check out the latest version (7.0.1). The default height has been increased to make it more visually noticeable.

**Comment by kdubb** [comment]
@fulstech Thanks for the quick update! Looks nice!
