### ISSUE TITLE
Rendering issue in JIRA links from Bitbucket Server

### ISSUE THREAD

**Issue by kdubb** [fulstech/markin#21]
We have Bitbucket Server linked to our JIRA instance. In BBS there is a link to related issues in JIRA.  When displaying an issue that has the description or comments field using Markin the display is nearly unreadable.  I realize this is in BBS and not JIRA, but they are an application suite and we need support across their products for Markin to be really useful to us.

Here is a screenshot of the problem (Notice the description field & configuration link):
<img width="825" alt="screen shot 2017-01-03 at 1 36 07 am" src="https://cloud.githubusercontent.com/assets/787655/21602812/3437033c-d155-11e6-9981-74c33738fca7.png">

**Comment by fulstech** [comment]
Hi @kdubb,

Just want to let you know that we are actively working on the issue. We appreciate all your great feedbacks and will release the new version as soon as possible.

**Comment by fulstech** [comment]
Hi @kdubb,

This bug has been fixed in version 8.0.0. If you have any other request, don't hesitate to let us know.

![bitbucket](https://cloud.githubusercontent.com/assets/17452401/22183232/94274afe-e0eb-11e6-9a32-fb4c7746a0f6.PNG)

**Comment by kdubb** [comment]
@fulstech This appears to be fixed, Thanks!
