### ISSUE TITLE
Loading the plugin takes forever

### ISSUE THREAD

**Issue by tfmf** [fulstech/markin#22]
Everytime an issue is viewed, Jira is downloading the minified js file for the plugin. The browser can't cache the js since a timestamp is appended to the request as you can see bellow:

```
GET /download/resources/com.fulstech.jira-gherkin-custom-field/js/tmp/all-20170122212937-min.js?_=1485345120469
```
This is causing Jira to operate really slow when viewing, navigating and updating issue.

Can you please remove the timestamp so that the browser can cache the js?

**Comment by fulstech** [comment]
@tfmf,

Thank you so much for your feedback. This issue has been fixed in version 8.0.1. If you have any other requests, we are happy to help.
