### ISSUE TITLE
Problem rendering links to other issues in the same JIRA instance

### ISSUE THREAD

**Issue by squierts** [fulstech/markin#25]
If say the description field of a issue references another issue by it's key, i.e. FOO-1, the plugin renders the text as "/browse/FOO-1" as regular text and not a href. There are two problems here. First, it isn't rendering as a href and secondly it shouldn't modify the text to be "/browse/FOO-1" but "FOO-1"

**Comment by fulstech** [comment]
Hi @squierts,

This bug has been fixed in version 8.1.0.

Thank you so much for using our product. If you have any other request, don't hesitate to let us know.
