### ISSUE TITLE
Wiki markup is not rendering correctly in Markin renderer fields

### ISSUE THREAD

**Issue by mendeelise** [fulstech/markin#26]
Wiki markup is not being rendered correctly in description and comment fields that are using the Markin Renderer. This issue may be happening in all fields using this renderer, but description and comment fields are the ones we have tested. Examples that are not being rendered correctly are:

{code}This should be rendered as a code block{code}
Etc. etc. blah blah blah {{this should be rendered as inline code}} blah blah blah

In the above examples the curly braces are rendering as regular characters and the content is not being formatted as code. 

The way it should render is:

```
This should be rendered as a code block
```

Etc. etc. blah blah blah `this should be rendered as inline code` blah blah blah

**Comment by mendeelise** [comment]
Just checking on the status of this issue. This is a show-stopper for our team. We are very eager to use this plugin.

**Comment by fulstech** [comment]
Hi @mendeelise,

Thank you so much for your feedback. The Atlassian Wiki's `{code}` syntax has been supported in the latest version - Markin 9.0.0. Besides, you can always use Markdown code block syntax.

![spl-10 as a developer i can update story and task status with drag and drop click the triangle at far left of this story to show sub-tasks - your company jira 1](https://cloud.githubusercontent.com/assets/17452401/24323784/a15c8ec6-11ad-11e7-9f45-3bb31fda06be.jpg)
![spl-10 as a developer i can update story and task status with drag and drop click the triangle at far left of this story to show sub-tasks - your company jira 2](https://cloud.githubusercontent.com/assets/17452401/24323785/a15d0ee6-11ad-11e7-9dc7-d1052df9ef9b.jpg)

If you have any other requests, do not hesitate to let us know.

Fulstech Team.

**Comment by mendeelise** [comment]
Perfect thank you! We will definitely be using markdown syntax for new issues. The wiki {code} support was for existing issues that we had created before installing your plugin. Thanks again for the quick turn-around.
