### ISSUE TITLE
Previous comment persists in the comment box

### ISSUE THREAD

**Issue by NeilLi1992** [fulstech/markin#27]
I get this problem when I'm on a issue detail view, and I add a Comment.
Now if wish to add a further comment by clicking the 'Comment' button, I can see my last comment stays there (the last comment actually got posted, it just feels like the comment box isn't cleaned up). If I simply delete things in the box, I can still post new comments without any problem.

I don't know if it's only happening for me, because this seems a very obvious issue. Could anyone help me if you get it working right?

**Comment by fulstech** [comment]
Hi @NeilLi1992,

This bug has been fixed in version 9.0.2.

Thank you so much for using our product. If you have any other request, don't hesitate to let us know.
