### ISSUE TITLE
Emails not formatted

### ISSUE THREAD

**Issue by mbohal** [fulstech/markin#28]
With the wiki renderer the emails coming from JIRA were nicely formatted. After switching to Markin we only get plain text.

I can not find this mentioned anywhere in the documentation. Is there any way to fix it?

**Comment by fulstech** [comment]
@mbohal,

Thank you so much for trying Markin. This is a limitation and we are working on the fix for the issue. Sorry for the inconvenience.

**Comment by mbohal** [comment]
I understand.

Is it reasonable to expect to have it fixed in some foreseeable future, or is it difficult and not likely to happen soon?

**Comment by fulstech** [comment]
@mbohal,

Do you use LaTeX, GraphViz, or Sequence Chart? The fix will be released next week for the Markdown and Gherkin parts. The reason is that complex charts and formulas take more time to render, and we need to make sure it does not affect JIRA servers considerably.

Markin Support

**Comment by mbohal** [comment]
We do not use any of the mentioned technologies.

Unfortunately our trial license expired and the majority of our team found the plugin not polished enough to buy it and keep using it. I still prefer Markin to the JIRA editor, but most of my colleagues do not feel the same way.

If you are interested, I can write down all the issues we found out for you.

I'm glad about the fix, but we wont be able to try it out due to expired trial license. Thanks for the reply though.

**Comment by fulstech** [comment]
@mbohal,

We are sorry for not building a better product for your team. We will be really happy to know about the issues you encountered so that we can make improvements to our product.

Thank you so much for trying our product and for your valuable feedback.
Fulstech Team
