### ISSUE TITLE
Issue search freezing when choosing from search results

### ISSUE THREAD

**Issue by gabeusse** [fulstech/markin#29]
Good Day,

I just updated to JIRA Software 7.4.0 from JIRA 7.3.6. After the update and the following configuration, I have discovered that when I perform a search query the following behavior appears.

1. The search results are shown, together with a render for the first issue that appears on the search list.

2. Once I click on another item from the search link, the side bar is grayed out and the issue is not rendered. The URL for the new issue is updated with the clicked issue number.

3. If I press enter on the updated URL, then the issue is correctly rendered.

4. The same behavior appears if I repeat this process on several issues from the search list.

I have disabled all the add-ons on my JIRA instance and found out that the wrong behavior was caused by the Markin add-on. It would be great if you can address this issue, as it is blocking the upgrade to the new JIRA version.

Thanks and best,

Juan Eusse

**Comment by fulstech** [comment]
Hi @gabeusse,

Thank you for the detailed reproduce steps. We are investigating the issue and the fix will be released soon.

Markin Support

**Comment by fulstech** [comment]
@gabeusse,

This bug has been fixed in version 9.0.3.

Thank you so much for using our product. If you have any other request, don't hesitate to let us know. Once again we apologize for any trouble this bug has caused.

Fulstech Support
