### ISSUE TITLE
Couldn't add comment with Markin field renderer from issue view

### ISSUE THREAD

**Issue by hooke** [fulstech/markin#3]
When I am in an issue view in Jira Software Server 7.1.4, and Marking editor is enabled as renderer for comment field, I couldn't add comment after writing it (button Add is disabled permanently)

But I can add comment in board view

**Comment by gfink57** [comment]
Duplicated in our test server: v7.1.0#71003.

**Comment by fulstech** [comment]
Thank you all for your feedback. I'm happy to inform that this bug has been fixed in version 1.3.1.
