### ISSUE TITLE
Avatar rendering problem 

### ISSUE THREAD

**Issue by gabeusse** [fulstech/markin#31]
Dear support,

when performing a user mention on the plugin, the autocompletion of the names has a strange behavior in which some avatars are incorrectly rendered depending on their size. User avatars that are shipped with JIRA are bigger than ones that are manually assigned, as can be seen in the attached figure.

Thanks for the continuous support!!!

Best Regards,

Juan Eusse
![disconnected3](https://user-images.githubusercontent.com/29866891/28262291-d0d08b7e-6ae2-11e7-8fdf-baf0c6e55451.png)

**Comment by fulstech** [comment]
@gabeusse,

This bug has been fixed in version 9.0.5.

Thank you so much for using our product. If you have any other request, don't hesitate to let us know. Once again we apologize for any trouble this bug has caused.

Fulstech Support

**Comment by gabeusse** [comment]
Dear Support,

I keep having the same issue, even though the update made it into our JIRA instance yesterday, could you please check if the bug/fix is really effective.

Best,

**Comment by fulstech** [comment]
@gabeusse,

Sorry for the inconvenience. Our development will investigate the issue and get back to you as soon as possible.

Thank you and best regards,

**Comment by fulstech** [comment]
@gabeusse,

We have released version 9.0.6. Could you please check if this fixes your issues?

Thank you and best regards,
Fulstech Support

**Comment by gabeusse** [comment]
Dear Fulstech support,

Yes I can confirm that this issue is gone with the new update.

Thanks!!!

Best,

Juan
