### ISSUE TITLE
Cannot resize or thumbnail image

### ISSUE THREAD

**Issue by alanclyeh** [fulstech/markin#33]
I can attach image thumbnail or define custom height/weight of image  by original JIRA renderer.
But  Markin seems didn't support these function. 

Do you have any plant to support thumbnail or custom height/weight of image?

**Comment by fulstech** [comment]
@alanclyeh,

The syntax `!<attachment_name>|thumbnail!1` renders the attachment as a thumbnail. In version 9.0.7 we have added thumbnail syntax to attachment autocomplete list for your convenience. We will consider supporting custom size in future releases.

Thank you so much for your valuable feedback.
Markin Support
