### ISSUE TITLE
Preview?

### ISSUE THREAD

**Issue by hmijail** [fulstech/markin#35]
Is there any chance that the markdown editor will get a preview capability?

**Comment by fulstech** [comment]
@hmijail,

Thank you for a great suggestion! We are working on it and will have a release soon.

Sincerely,
Markin Support

**Comment by dgellow** [comment]
Great, that's also something we want 👍

**Comment by fulstech** [comment]
Hi,

We are happy to inform that the Preview mode has been added to version 10.0.0. Thank you again for a great suggestion, and we are looking forward to your feedback.

Sincerely,
Markin Support

**Comment by dgellow** [comment]
We updated, the preview is working. Thank you for this.
