### ISSUE TITLE
Migrate old JIRA tasks to Markdown?

### ISSUE THREAD

**Issue by dgellow** [fulstech/markin#36]
Hello there,

We are evaluating Markin to replace the default renderer in JIRA. Do you have a way to easily convert old JIRA tasks from JIRA markup language to markdown? That would greatly simplify our migration process :)

**Comment by fulstech** [comment]
Hi @dgellow,

Markin supports rendering a limited set of Atlassian syntax - no conversion is needed. The support is expanded based on users' demand. In general, we would suggest that customers should create new Markdown fields and leave the Atlassian Wiki ones intact to avoid vendor lock-in situations.

Thank you and best regards,
Fulstech Support
