### ISSUE TITLE
Comments with Markin editor renderer are not shown in board view

### ISSUE THREAD

**Issue by hooke** [fulstech/markin#4]
When Markin editor is chosen as a renderer for comment field, I couldn't see comments in board view, see image:
![image](https://cloud.githubusercontent.com/assets/248268/14492025/262f177a-0185-11e6-899c-23716ef43c7e.png)

**Comment by gfink57** [comment]
Duplicated in our test server: v7.1.0#71003, Markin 1.2.0.

**Comment by fulstech** [comment]
Thank you all for your feedback. I'm happy to inform that this bug has been fixed in version 1.3.1.
