### ISSUE TITLE
LaTex plugin for Confluence has stopped working

### ISSUE THREAD

**Issue by meowcakes** [fulstech/markin#43]
Hello,

Currently, when a Confluence page with LaTex in it loads, the LaTex never loads and remains as the spinning loading icon.

The console is filled with these error messages:
```
[Simple-XDM] Failed to validate origin: https://latexmath-connect-lite.aerobaticapp.com
RPC: request rejected (bad origin): https://latexmath-connect-lite.aerobaticapp.com
```

Thanks

**Comment by fulstech** [comment]
Hi,

It seems that the URL belongs to this plugin https://marketplace.atlassian.com/plugins/com.tensixtwo.conf.latexmath-lite/cloud/overview (not Fulstech's one). Could you please check again?

Thank you and best regards,
Fulstech Support

**Comment by meowcakes** [comment]
Ah, very sorry!
