### ISSUE TITLE
Bug: Faulty Table display with Markin

### ISSUE THREAD

**Issue by huettenhain** [fulstech/markin#44]
I am having some troubles displaying tables in Markin. 

I include a minimal example with a screenshot of how it is rendered. Below I used the same code to display the desired result produced by Github's rendering.

## Example Code

    # Bug 1

    The data is not displayed correctly

    ## With no bars left and right

     Domain                   | IP Address                 
     ------------------------ | ----------------
     `domain[.]tld`           | `127.0.0[.]1`
     `domain[.]tld`           | `127.0.0[.]1`

    ## With no bars only to the right

     Domain                   | IP Address       |              
     ------------------------ | ---------------- |
     `domain[.]tld`           | `127.0.0[.]1`    |
     `domain[.]tld`           | `127.0.0[.]1`    |
     
    ## With bars left and right

    | Domain                   | IP Address      |              
    | ------------------------ | --------------- |
    | `domain[.]tld`           | `127.0.0[.]1`   |
    | `domain[.]tld`           | `127.0.0[.]1`   |

    # Bug 2

    When tables have bars left and right, the separator line is rendered as a row, which is incorrect:

    | Name           | Color        |
    | -------------- | ------------ |
    | Ralph          | Blue         |
    | Anne           | Red          |

## Markin Rendering

![markin bug](https://user-images.githubusercontent.com/11869704/36721903-7a8a0512-1bac-11e8-9fc5-0d6268e749fc.png)

## Desired Rendering

# Bug 1

The data is not displayed correctly

## With no bars left and right

 Domain                   | IP Address                 
 ------------------------ | ----------------
 `domain[.]tld`           | `127.0.0[.]1`
 `domain[.]tld`           | `127.0.0[.]1`

## With no bars only to the right

 Domain                   | IP Address       |              
 ------------------------ | ---------------- |
 `domain[.]tld`           | `127.0.0[.]1`    |
 `domain[.]tld`           | `127.0.0[.]1`    |
 
## With bars left and right

| Domain                   | IP Address      |              
| ------------------------ | --------------- |
| `domain[.]tld`           | `127.0.0[.]1`   |
| `domain[.]tld`           | `127.0.0[.]1`   |

# Bug 2

When tables have bars left and right, the separator line is rendered as a row, which is incorrect:

| Name           | Color        |
| -------------- | ------------ |
| Ralph          | Blue         |
| Anne           | Red          |

**Comment by fulstech** [comment]
Thank you so much for the feedback. We've released version 10.0.2 to address this bug. If you have any issue kindly let us know.

Sincerely,
Fulstech Support

**Comment by huettenhain** [comment]
works fine, thanks!
