### ISSUE TITLE
Severe bug; JavaScript Injection

### ISSUE THREAD

**Issue by huettenhain** [fulstech/markin#45]
I have encountered a severe bug with the Markin plugin in Jira. The following legitimate Markdown snippet:

    ```
    <html><script>alert('cross-site scripting')</script>
    ```

will not only break the entire Ticket page when it is rendered in a Markin field, it does also execute the embedded JavaScript. It would be really great if this could be fixed as soon as possible.

This is not only a security risk but a very severe practical problem in our case: We can not write any Markin content with code snippets that contain `<html>`, because it will also break the ticket display completely. However, that does come up quite frequently, so it boils down to rendering (no pun intended) Markin unusable.

**Comment by huettenhain** [comment]
I just realized this is related to #40.

**Comment by fulstech** [comment]
Thank you so much for the valuable feedback. A new version will be released this week to address this issue.

Sincerely,
Fulstech Support

**Comment by fulstech** [comment]
Thank you so much for the feedback. We've released version 10.0.2 to address this bug. If you have any issue kindly let us know.

Sincerely,
Fulstech Support

**Comment by huettenhain** [comment]
Seems to be fixed, thanks!
