### ISSUE TITLE
Line is not wrapped for a paragraph.

### ISSUE THREAD

**Issue by hooke** [fulstech/markin#5]
When I am typing a paragraph of text, I do not press `Enter` to wrap the visible line, editor does it for me. For example, Github editor. 

In Markin editor, I have one very long line when typing one big paragraph of text.

Is not comfy. Please add some wrapping.

**Comment by fulstech** [comment]
Thank you all for your feedback. I'm happy to inform that line wrapping has been supported in version 1.3.1.
