### ISSUE TITLE
When we can expect Data Center version release?

### ISSUE THREAD

**Issue by Kaleeswari-G** [fulstech/markin#59]
Hi Team,

     We are using Jira 8.0.2 Data Center version. As we are in need of your plugin, could you please provide an ETA of your add-on "Markin - Markdown Custom Field for JIRA" release which will be compatible with DC approved for version 8.0.2?

Regards,
Kaleeswari G

**Comment by fulstech** [comment]
The Data Center version is available now. Thank you for your feedback.
