### ISSUE TITLE
Feature request: monospace font when displaying Markin field text

### ISSUE THREAD

**Issue by yoshikin** [fulstech/markin#6]
When editing text in a Markin field a monspaced font is used. After saving the changes, however, the monospace font disappears and the standard Jira font (in my case Arial) is used to display the text.

I actually prefer the monospaced font for showing Gherkin text. Is it possible to get the field to use the same monospace font ofr both editing and displaying text without doing custom CSS hacks?

Examples:

**While editing:**

![image](https://cloud.githubusercontent.com/assets/10310897/14782023/b1a36256-0ae6-11e6-9c69-578c2bbc75f4.png)

**After changes saved:**

![image](https://cloud.githubusercontent.com/assets/10310897/14782033/cfb97de8-0ae6-11e6-81c5-f183aac71491.png)

**Comment by fulstech** [comment]
Joshua,

Thank you so much for your feedback. To accommodate different preferences, we will add an option so that users can select their font of choice in the next version, which was scheduled to be released next Monday.

**Comment by yoshikin** [comment]
Great. Will users also be able to specify a css font-family such as "monospace" instead of a particular font?

We are running Jira Server with no custom css and in the edit view today the Markin field appears to be using `font-family:monospace`.

**Comment by fulstech** [comment]
Thank you for the response. We planned to allow only two options: "monospace" and "non-monospace", so that we can still keep Markin's UI consistent with JIRA's UI. Does it satisfy your needs?

**Comment by yoshikin** [comment]
Yes, thanks. That is exactly what I was thinking.

**Comment by yoshikin** [comment]
What is the status of this? It doesn't seem to be available in the latest version yet?

**Comment by yoshikin** [comment]
Is this feature still planned?

**Comment by fulstech** [comment]
Yoshikin,

I sincerely apology for the very long delay. This feature has been released in version 4.0.0. When user hovers on Markin content, the link to configure page will be shown. The setting is per user and per field.

If this design does not meet your demand, feel free to share your opinion. We always appreciate your suggestions and requests.

![test-1 test - your company jira](https://cloud.githubusercontent.com/assets/17452401/18411436/a8f94d78-77a1-11e6-8d4a-0835093816a9.jpg)

![configure markin editor for field description - your company jira](https://cloud.githubusercontent.com/assets/17452401/18411463/0c15e2c2-77a2-11e6-83e6-f35d4208cd85.jpg)

**Comment by fulstech** [comment]
Yoshikin,

I'm getting back to see if this feature meets your needs. If you have any issue, feel free to let us know. Thank you a lot for trying our product.

**Comment by yoshikin** [comment]
Yes, thank you for adding this feature.

**Comment by kdubb** [comment]
@fulstech Is there a way to hide the floating `Configure the way this content is displayed`? It's actually fairly annoying to see as you move around the fields in JIRA.  Can this not be put on the plugin configuration page instead?

**Comment by fulstech** [comment]
@kdubb,

We will move it to a better place in the future. In the meanwhile, in the latest version (7.0.1) the style has been updated to make the link less noticeable when hovering on the corresponding field.
