### ISSUE TITLE
Newline doesn't work properly

### ISSUE THREAD

**Issue by Minwoo-Kang** [fulstech/markin#66]
This is how the desc looks when I am writing it:
​​​​​​​​​​
![newline_error_1](https://user-images.githubusercontent.com/19739715/68812118-7e895c80-06b5-11ea-82a9-360ea6600f6e.png)

This is how the issue looks once it is saved:

![newline_error_2](https://user-images.githubusercontent.com/19739715/68812119-80532000-06b5-11ea-8990-113bc58fbc35.png)

The workaround is to use a backslash for each line break.  This is not sufficient.  Please address asap.

**Comment by fulstech** [comment]
We will upload the new version in a few hours to address this issue.

**Comment by fulstech** [comment]
The new version (11.0.0) has been uploaded. This feature must be enabled before using.

Hover on a field, the link to the Settings page will be shown at the bottom.

![image](https://user-images.githubusercontent.com/17452401/69733625-3744a680-1160-11ea-9940-fcf8432780bc.png)

![image](https://user-images.githubusercontent.com/17452401/69733637-3b70c400-1160-11ea-8e65-7c9577bbdf70.png)

**Comment by Minwoo-Kang** [comment]
Really thank you for your appreciation.
